[package]
name = "structopt-examples"
version = "0.1.0"
authors = ["Capella <52690366+capella903@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
